// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FriendshipController from "./friendship_controller"
application.register("friendship", FriendshipController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchUniversesController from "./search_universes_controller"
application.register("search-universes", SearchUniversesController)
