// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExpanderStoriesController from "./expander_stories_controller"
application.register("expander-stories", ExpanderStoriesController)

import FriendshipController from "./friendship_controller"
application.register("friendship", FriendshipController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
